# Generated by Django 3.0.3 on 2020-06-18 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_blog', '0003_auto_20200601_2225'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='blog_image',
            field=models.ImageField(upload_to='', verbose_name='Blog Image'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='comment',
            field=models.TextField(verbose_name='Type Your Comment:'),
        ),
    ]
